### ISSUE TITLE
Error message returns

### ISSUE THREAD

**Issue by ScrumpyJack** [ltb-project/ppm#3] opened 2016-11-09 11:23 UTC
It seems that when the ldap client fails to match the defined password requirements, any error messages such as PASSWORD_TOO_LONG_SZ in ppm are not passed on to the client. The client errors with "Can't contact LDAP server"

I'm not too sure how this works, but it's not returning the error message. Is that what you expect?

```
  fail:
    *ppErrStr = strdup(szErrStr);
    ber_memfree(szErrStr);
    return (EXIT_FAILURE);
```

Also there is a typo on line 368
```    diff --git a/ppm.c b/ppm.c
    index 1193e6b..55c40f4 100644
    --- a/ppm.c
    +++ b/ppm.c
    @@ -365,7 +365,7 @@ check_password(char *pPasswd, char **ppErrStr, Entry * pEntry)
     {
     #if defined(DEBUG)
    -    syslog(LOG_NOTICE, "ppm: Entry %s", pEntry->e_nname.bv_val);
    +    syslog(LOG_NOTICE, "ppm: Entry %s", pEntry->e_name.bv_val);
     #endif
         char *szErrStr = (char *) ber_memalloc(MEM_INIT_SZ);

```

**Comment by davidcoutadeur** [comment] 2016-11-09 11:33
Hi ScrumpyJack,

I don't think the e_nname is a typo, please see the API documentation:
https://fossies.org/dox/openldap-2.4.44/structEntry.html

The "Can't contact LDAP server" means OpenLDAP has crashed because of a grave error.
An error in the configuration or in the path of certain files can be the cause. Try to set a debug level and check where the module has crashed.

**Comment by ScrumpyJack** [comment] 2016-11-09 11:53
thanks for your response david.
The openldap server logs show the connection and show ppm working just fine (rejecting a password), but the client gets "Can't contact LDAP server". If the client then tries to need the password requirements configured in PPM, he can change his password. The ldap clients is openldap2-client-2.2.24

**Comment by davidcoutadeur** [comment] 2016-11-09 13:08
Your LDAP client has to interprete LDAP ppolicy extended error messages.
Do you use "-e ppolicy" during the modification ?
I also suggest you use the last version of OpenLDAP server and client. did you give a try with OpenLDAP-LTB RPM / DEB packages ? http://ltb-project.org/wiki/documentation

**Comment by ScrumpyJack** [comment] 2016-11-09 14:54
client is pam_ldap
I'll dig around and find out how to get it to use the extended error messages API

**Comment by stejamtro** [comment] 2016-11-15 19:28
Hi David, Thanks for responding to ScrumpyJack, your comments were really useful, however he's constrained by the need to use openldap-2.4.26 for both server and client (please don't ask !) and is doing this on a sles11 platform (rpm not deb I'm afraid, which makes the task a bit harder) The source for the openldap he is **forced** to use compiles ok with your module copied into the slapd-modules sub directory and produces a **ppm.so** object nicely, as SJ says above it works when called but doesn't reflect messages back to the user. So...........you mention using **"-e ppolicy"** during the modification, is this passed to make (shell environment variable override) ? or at some other place in the process: "LDAP Parameters" or some such like ? **A**ny help or direction that you can give would be much appreciated. Thanks a lot.

**Comment by davidcoutadeur** [comment] 2016-11-15 19:57
no, "-e ppolicy" is a parameter to pass to ldapmodify command in order to interpret ppolicy messages sent by the OpenLDAP server.

**Comment by stejamtro** [comment] 2016-12-08 13:59
Hi again David, we're using  openldap2-2.4.26-0.12.1, do you know if this version supports what you suggest please: 'ldapmodify -e ppolicy'
Thanks.

**Comment by davidcoutadeur** [comment] 2016-12-09 20:13
As far as I know, ppolicy is an old extension, so I suppose it is supported in version 2.4...

**Comment by davidcoutadeur** [comment] 2017-05-31 16:33
The initial problem (which was not a problem eventually) has been solved a long time ago, so closing the issue.

**Closed as completed by davidcoutadeur** 2017-05-31 16:33 UTC
